/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package androidx.room.vo

import androidx.room.compiler.processing.XMethodElement
import androidx.room.compiler.processing.XType
import androidx.room.solver.transaction.binder.TransactionMethodBinder

class TransactionMethod(
    val element: XMethodElement,//transaction方法
    val returnType: XType,//transaction方法返回类型
    val parameterNames: List<String>,//transaction方法参数
    val callType: CallType,
    val methodBinder: TransactionMethodBinder//绑定对象
) {
    enum class CallType {
        /**
         * Directly call the method, it has an implementation
         *
         * 直接调用方法，它有一个实现
         */
        CONCRETE,

        /**
         * It has a default implementation and the default implementation is in the DAO
         *
         * 它有一个默认实现，默认实现在DAO中
         */
        DEFAULT_JAVA8,

        /**
         * Has DefaultImpl generated by kotlin
         *
         * 具有由kotlin生成的DefaultImpl
         */
        DEFAULT_KOTLIN,

        /**
         * It has a default implementation which is not declared in the dao, rather, it inherits
         * it from a super.
         *
         * 它有一个没有在dao中声明的默认实现，而是从一个超级继承了它。
         */
        INHERITED_DEFAULT_JAVA8
    }
}
